# Generated by Django 3.2.4 on 2021-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotstaskcontrol',
            name='status',
            field=models.CharField(default='unpublished', max_length=20, verbose_name='任务状态'),
        ),
    ]
